[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
infrastructure = { path = "../infrastructure" }
application = { path = "../application" }
domain = { path = "../domain" }

axum = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"]}
tower = { workspace = true }
serde = { workspace = true , features = ["derive"]}
serde_json = { workspace = true }
uuid = { workspace = true , features = ["v4"] }
