[package]
name = "domain"
version = "0.1.0"
edition = "2024"

[dependencies]

uuid =  { workspace = true , features = ["v5"]}
thiserror =  { workspace = true }
async-trait =  { workspace = true }
url =  { workspace = true }
chrono = { workspace = true, features = ["serde"] }
